#!/usr/bin/env bash
# pi_auth_setup.sh
# ----------------------------------------------------------------
# Generate (or rotate) the bearer token that protects the WS bus
# from unauthenticated access, and wire it into the bridge
# systemd unit.
#
# Why this matters: the WS bridge binds 0.0.0.0:81 today. On the
# home AP that's fine because WPA2-PSK is the perimeter, but the
# moment the bridge is reachable over Tailscale (or, later, LTE),
# every device on the same tailnet can drive the robot by default.
# A short bearer token closes that gap.
#
# Steps:
#   1. On the Pi:  sudo bash pi_auth_setup.sh
#      -> Writes /etc/climbingrobot/auth_token with a fresh 256-bit
#         random token. Mode 640, root:root.
#      -> Adds /etc/systemd/system/serial-bridge.service.d/10-auth.conf
#         pointing EnvironmentFile= at the token file.
#      -> Restarts serial-bridge.service so it picks up the token.
#
#   2. Pull the token onto any operator machine:
#        scp pi@<pi-ip>:/etc/climbingrobot/auth_token ~/.config/climbingrobot/auth_token
#        chmod 600 ~/.config/climbingrobot/auth_token
#
#   3. Point the dashboard / gamepad sender at the bridge with the
#      token via --auth-token or BRIDGE_AUTH_TOKEN env var.
#        python3 mac_dashboard.py --host 192.168.4.1 \\
#                                --auth-token "$(cat ~/.config/climbingrobot/auth_token)"
#
# Pass --rotate on subsequent runs to mint a new token and restart
# the bridge. Existing dashboard / gamepad clients will be rejected
# until they pull the new token from the Pi.
# ----------------------------------------------------------------
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "Re-run as root: sudo $0" >&2
  exit 1
fi

ROTATE=0
if [[ "${1:-}" == "--rotate" ]]; then
  ROTATE=1
fi

CONFIG_DIR="/etc/climbingrobot"
TOKEN_FILE="${CONFIG_DIR}/auth_token"
OVERRIDE_DIR="/etc/systemd/system/serial-bridge.service.d"
OVERRIDE_FILE="${OVERRIDE_DIR}/10-auth.conf"

install -d -m 0750 -o root -g root "${CONFIG_DIR}"

if [[ -f "${TOKEN_FILE}" && "${ROTATE}" -ne 1 ]]; then
  echo "[*] ${TOKEN_FILE} already exists (use --rotate to regenerate)"
  TOKEN="$(cat "${TOKEN_FILE}")"
else
  # 256 bits of entropy, base64-url-safe. The bridge does constant-
  # time compare, so length doesn't matter for the protocol but a
  # 32-byte value is the convention.
  echo "[*] Generating new bearer token"
  TOKEN="$(head -c 32 /dev/urandom | base64 | tr -d '+/=' | head -c 43)"
fi

# systemd's EnvironmentFile expects KEY=VALUE lines. Write it that way
# so a future operator can `cat` it without leaking the token shape
# (no leading "token:" or "Bearer:" prefix to grep for in dmesg etc.).
printf 'BRIDGE_AUTH_TOKEN=%s\n' "${TOKEN}" > "${TOKEN_FILE}"
chmod 0640 "${TOKEN_FILE}"
chown root:root "${TOKEN_FILE}"

echo "[*] Token written to ${TOKEN_FILE} (mode 0640)"

echo "[*] Installing systemd override -> ${OVERRIDE_FILE}"
install -d -m 0755 "${OVERRIDE_DIR}"
cat > "${OVERRIDE_FILE}" <<EOF
# Generated by pi_auth_setup.sh. Forces the WS bridge to require an
# Authorization: Bearer <token> header on every upgrade. Required
# whenever the bridge is reachable over an untrusted network.
[Service]
EnvironmentFile=${TOKEN_FILE}
EOF

# The bridge already reads $BRIDGE_AUTH_TOKEN from its own --auth-token
# default, so we don't have to change ExecStart -- just reloading the
# unit picks the new env var up.
systemctl daemon-reload
systemctl restart serial-bridge.service

echo
echo "[*] Bridge status (auth line)"
journalctl -u serial-bridge.service --no-pager -n 5 | grep -i 'auth=' || true

cat <<EOF

[ok] Token:  ${TOKEN_FILE}
     Override unit: ${OVERRIDE_FILE}

Pull it onto your operator laptop:
  scp ${SUDO_USER:-pi}@\$(hostname):${TOKEN_FILE} \\
     ~/.config/climbingrobot/auth_token

Then run the dashboard with it:
  export BRIDGE_AUTH_TOKEN="\$(cat ~/.config/climbingrobot/auth_token)"
  python3 mac_dashboard.py --host 192.168.4.1

(Or skip the export and pass --auth-token directly.)

EOF